# Generated by Django 2.1.1 on 2018-09-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SteamGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.IntegerField(help_text='Id do jogo na Steam', verbose_name='steamId')),
                ('name', models.CharField(help_text='Id do jogo na Steam', max_length=100, verbose_name='name')),
                ('average_2weeks', models.IntegerField(help_text='Average time played in two Weeks', verbose_name='Average Time Played 2 Weeks')),
            ],
        ),
    ]
