# Generated by Django 2.1.1 on 2018-09-02 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='steamgame',
            options={'verbose_name': 'Steam Game', 'verbose_name_plural': 'Steam Games'},
        ),
    ]
