# Generated by Django 2.1.1 on 2018-09-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0002_auto_20180902_2006'),
    ]

    operations = [
        migrations.CreateModel(
            name='IGDBGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igdbGame_id', models.IntegerField(help_text='Id do jogo na IGDB', verbose_name='IGDB ID')),
                ('name', models.CharField(help_text='Nome do Jogo', max_length=100, verbose_name='name')),
                ('hypes', models.IntegerField(help_text='Number of access in the game befores its release', verbose_name='Hypes')),
            ],
            options={
                'verbose_name': 'IGDB Game',
                'verbose_name_plural': 'IGDB Games',
            },
        ),
        migrations.DeleteModel(
            name='SteamGame',
        ),
    ]
