# Generated by Django 2.1.1 on 2018-09-04 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0003_auto_20180904_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.IntegerField(help_text='Genre id at IGDB', primary_key=True, serialize=False, verbose_name='Genre ID')),
                ('name', models.CharField(help_text='Genre name', max_length=100, verbose_name='Genre name')),
            ],
        ),
        migrations.RemoveField(
            model_name='igdbgame',
            name='igdbGame_id',
        ),
        migrations.AddField(
            model_name='igdbgame',
            name='aggregated_rating',
            field=models.FloatField(help_text='Rating based on external critic scores', null=True, verbose_name='Critics Rating'),
        ),
        migrations.AddField(
            model_name='igdbgame',
            name='popularity',
            field=models.FloatField(help_text='Popularity of game', null=True, verbose_name='Popularity'),
        ),
        migrations.AddField(
            model_name='igdbgame',
            name='time_to_beat',
            field=models.FloatField(help_text='Avarage time to beat the game', null=True, verbose_name='Time To Beat'),
        ),
        migrations.AlterField(
            model_name='igdbgame',
            name='hypes',
            field=models.IntegerField(help_text='Number of access in the game befores its release', null=True, verbose_name='Hypes'),
        ),
        migrations.AlterField(
            model_name='igdbgame',
            name='id',
            field=models.IntegerField(help_text='Id do jogo na IGDB', primary_key=True, serialize=False, verbose_name='IGDB ID'),
        ),
        migrations.AlterField(
            model_name='igdbgame',
            name='name',
            field=models.CharField(help_text='Name of game', max_length=100, null=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='igdbgame',
            name='genres',
            field=models.ManyToManyField(null=True, to='importdata.Genre'),
        ),
    ]
