# Generated by Django 2.1.1 on 2018-09-06 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0005_auto_20180905_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='igdbgame',
            name='steam',
            field=models.IntegerField(null=True, verbose_name='Steam Id'),
        ),
        migrations.AlterField(
            model_name='igdbgame',
            name='genres',
            field=models.ManyToManyField(blank=True, to='importdata.Genre'),
        ),
    ]
