# Generated by Django 2.1.1 on 2018-09-10 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importdata', '0006_auto_20180906_1604'),
    ]

    operations = [
        migrations.CreateModel(
            name='IGDBKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='key to make requests on IGDB API', max_length=100, verbose_name='IGDB Key')),
                ('requests_count', models.IntegerField(help_text='Number of times this key has been used', verbose_name='Requests Count')),
                ('available', models.BooleanField(default=False)),
            ],
        ),
    ]
