version: '3.5'

services:
  igdbdb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - proxynet
  igdbweb:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - igdbdb
    networks:
      - proxynet
    environment:
      - COVERALLS_REPO_TOKEN

   metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    networks:
      - proxynet
networks:
  proxynet:
    name: GamesBI-network
