version: '3'

services:
  db:
    image: mongo
    ports:
      - "27017:27017"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
<<<<<<< d9f8c76f5e04d09e61c8726efc67fa620ee9bb95
      - db


=======
      - db
>>>>>>> [UPDATE] HOTFIX Updated requirements and docker compose to run mongodb
